
version: 2.1

jobs:
  integration-snowflake:
    docker:
      - image: cimg/python:3.9

    resource_class: small

    steps:
      - checkout
      - run: pip install --pre dbt-snowflake -r dev-requirements.txt
      - run: /.bashrc
      - run: chmod +x run_test.sh
      - run:
          name: "Run OG Tests - Snowflake"
          command: ./run_test.sh
      - store_artifacts:
          path: integration_tests/logs          
      - store_artifacts:
          path: integration_tests/target

workflows:
  version: 2
  continuous-integration:
    jobs:
      - integration-snowflake