integration_tests:
  outputs:
    snowflake:
      account: ${SNOWFLAKE_ACCOUNT}
      database: ${SNOWFLAKE_DATABASE}
      password: ${SNOWFLAKE_PASSWORD}
      role: ${SNOWFLAKE_ROLE}
      schema: ${SNOWFLAKE_SCHEMA}
      threads: 4
      type: snowflake
      user: ${SNOWFLAKE_USER}
      warehouse: ${SNOWFLAKE_WAREHOUSE}
  target: snowflake
  
    postgres:
        type: postgres
        host: localhost
        user: postgres
        password: jman
        port: 5434
        dbname: test_profiling
        schema: profiling
        threads: 4
  target: postgres