integration_tests:
  outputs:
    postgres:
        type: postgres
        host: localhost
        user: root
        password: test
        port: 5432
        database: profiling_test
        schema: test
        threads: 1
  target: postgres